scalar DateTime

type Query {
    getPost(id: ID!): Post
    indexPost(ids: [ID]): [Post]
}

type Mutation {
    createPost(postCreateInput: PostCreateInput!): Post!
    updatePost(postUpdateInput: PostUpdateInput!): Post!
    deletePost(postDeleteInput: PostDeleteInput!): MutationResult!
}

type Post {
    id: ID!
    title: String!
    body: String!
    createDate: DateTime!
    updateDate: DateTime!
}

type MutationResult {
    errorCode: String!
    validationError: [ValidationError]
}

type ValidationError {
    fieldName: String!
    validationCode: String!
}

input PostCreateInput {
    title: String!
    body: String!
}

input PostUpdateInput {
    id: ID!
    title: String
    body: String
}

input PostDeleteInput {
    id: ID!
}